***
**Introduction to Machine Learning** <br>
__[https://slds-lmu.github.io/i2ml/](https://slds-lmu.github.io/i2ml/)__
***

# The Pandas package

Additional reading material: https://conference.scipy.org/proceedings/scipy2010/pdfs/mckinney.pdf

## 1. Series

### a) Create a series from a list

In [95]:
import numpy as np
import pandas as pd

# Create labels (list)
labels = ['a','b','c']

# Create data (list)
my_list = [10,20,30]

# Convert the list
pd.Series(data = my_list)

# Convert the list and the labels
pd.Series(data = my_list, index = labels)

# Shorter version; less clean but the same result:
pd.Series(my_list, labels)

a    10
b    20
c    30
dtype: int64

### b) Create a series from a NumPy array

In [96]:
# Convert a list to a NumPy array
arr = np.array(my_list)

# Convert a NumPy array to a Pandas series
ser = pd.Series(arr)
ser

0    10
1    20
2    30
dtype: int64

In [97]:
# Convert a NumPy array to a pandas series - with labels
ser = pd.Series(data = arr, index = labels)
ser

a    10
b    20
c    30
dtype: int64

### c) Create a series from a dictionary

In [98]:
# Create a dictionary with similar data
d = {'a' : 10,
    'b' : 20,
    'c' : 30}

# Convert the dictionary to a series
ser = pd.Series(d)
ser

a    10
b    20
c    30
dtype: int64

### d) Data types in a series

In [99]:
# Besides numbers, strings can also be stored in a series...
ser_str = pd.Series(data = labels)
# ... also mixtures of numbers and strings:
pd.Series(data = [1, 'a'])

0    1
1    a
dtype: object

In [100]:
# ... even functions are possible
ser_func = pd.Series([sum,print])
ser_func

0      <built-in function sum>
1    <built-in function print>
dtype: object

In [101]:
# The data type of elements stored in the series can be seen
# either with printing the output or with .dtype
ser_str.dtype

dtype('O')

### e) Using index

In [102]:
# Create series 1
ser1 = pd.Series(data = [1,2,3,4],
                index = ['FCB', 'B04', 'BVB', 'S04'])

# The index and the values can be returned separately:
ser1.index

Index(['FCB', 'B04', 'BVB', 'S04'], dtype='object')

In [103]:
ser1.values

array([1, 2, 3, 4])

In [104]:
# Access either with square brackets or index...
ser1['FCB'] # or ser1.loc['FCB']

1

In [105]:
# ... or a line number
ser1[0] # or ser1.iloc[0]

1

In [106]:
# Create series 2
ser2 = pd.Series(data = [1,2,5,4],
                index = ['FCB', 'B04', 'TSV', 'SVW'])

# Operations are performed based on the index:
summe = ser1 + ser2
summe

B04    4.0
BVB    NaN
FCB    2.0
S04    NaN
SVW    NaN
TSV    NaN
dtype: float64

In [107]:
# The missing value for pandas is np.nan, as in NumPy,
# even if it is displayed as nan in the print mode:
summe[1]

nan

In [108]:
np.isnan(summe[1]) # Warning=> not like this: summe[1] == np.nan

True

### f) Mixed data types in list, NumPy array, Pandas series

In [109]:
# Python list
liste = [1, 2, 'a']
# NumPy array
arr = np.array(liste)
# Pandas series
ser = pd.Series(liste)
liste[0]

1

In [110]:
arr[0]

'1'

In [111]:
ser[0]

1

In [112]:
# Type conversion in python for String -> Numeric
int('1')

1

In [113]:
# The pandas function .to_numeric converts the type of entire columns
pd.to_numeric(pd.Series(['1', '2', '3']))

0    1
1    2
2    3
dtype: int64

In [114]:
pd.to_numeric(pd.Series(['1', '2', '3'])).astype('float') # int -> float

0    1.0
1    2.0
2    3.0
dtype: float64

⇒ For more type conversions, check e.g.,
https://www.geeksforgeeks.org/type-conversion-python/

In [115]:
# Conversion Pandas Series -> Numpy Array
print(ser)

0    1
1    2
2    a
dtype: object


In [116]:
np.array(ser)

array([1, 2, 'a'], dtype=object)

In [117]:
# Conversion Numpy Array -> List
list(np.array(ser))

[1, 2, 'a']

## 2. DataFrames

### a) Create a DataFrame

In [118]:
from numpy.random import randn
np.random.seed(101)

df = pd.DataFrame(data = randn(3,4),
                index = 'A B C'.split(),
                columns = 'W X Y Z'.split())
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001

In [119]:
df.index # Row names

Index(['A', 'B', 'C'], dtype='object')

In [120]:
df.columns # Column names

Index(['W', 'X', 'Y', 'Z'], dtype='object')

In [121]:
df.values # Values only - without row and column names

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053]])

### b) Selecting columns

In [122]:
# Use single square brackets to select a column by its name
df['W']

A    2.706850
B    0.651118
C   -2.018168
Name: W, dtype: float64

In [123]:
# Or several columns by their names: with a list
df[['W','Z']]

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001

In [124]:
# Alternative
df.W

A    2.706850
B    0.651118
C   -2.018168
Name: W, dtype: float64

In [125]:
# Use .iloc to select columns based on their order numbers;
# the colon indicates that all rows in that column will be selected
df.iloc[:,2] # [rows, columns]

A    0.907969
B   -0.848077
C    0.528813
Name: Y, dtype: float64

In [126]:
# Use .loc to select rows and columns based on their names
df.loc[:,'W']

A    2.706850
B    0.651118
C   -2.018168
Name: W, dtype: float64

In [127]:
# Columns of a data frame are Series:
type(df['W'])

pandas.core.series.Series

### c) Selecting rows

In [128]:
# Use .iloc to select rows based on their numbers
df.iloc[2]

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

In [129]:
# Use .loc to select rows based on their index (names)
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [130]:
# or - cleaner
df.iloc[2,:]
df.loc['A',:]

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

### d) Selecting a subset of rows and columns

In [131]:
# With .loc you can select rows and columns,
# separated by commas based on the name
df.loc['B','Y']

-0.8480769834036315

In [132]:
# ... also several from each
df.loc[['A','B'],
    ['W','Y']]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

In [133]:
# ... including individual columns (3rd option for (b))
df.loc[:,'W']
# => With .loc and .iloc, a row is addressed only if one element is given

A    2.706850
B    0.651118
C   -2.018168
Name: W, dtype: float64

In [134]:
# With .iloc you can select rows and columns,
# separated by commas based on the indexes
df.iloc[1, 2]

-0.8480769834036315

In [135]:
# ... also several from each
df.iloc[[0,1],
    [0,2]]

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

In [136]:
# ... or:
df.iloc[0:2,1:3]

X         Y
A  0.628133  0.907969
B -0.319318 -0.848077

### e) Conditional selection => like in R:

In [137]:
df # data frame from above

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001

In [138]:
# Which values are positive?
df > 0

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False

In [139]:
# Keep only positive ones
df[df > 0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN

In [140]:
# How many values are positive?
# ... per column
(df > 0).sum() # 'axis = 0' is the default

W    2
X    2
Y    2
Z    2
dtype: int64

In [141]:
# ... per row
(df > 0).sum(axis = 1) # Sum in the column direction

A    4
B    2
C    2
dtype: int64

In [142]:
# ... in total
(df > 0).sum().sum()

8

In [143]:
# Keep all rows for which column W is positive
df[df['W'] > 0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965

In [144]:
# Then, keep only column Y of that
df[df['W'] > 0]['Y']

A    0.907969
B   -0.848077
Name: Y, dtype: float64

In [145]:
# Several conditions can be combined (as in R) with | and &
# Only rows for which column W is positive and column Y is positive
df[(df['W'] > 0) & (df['Y'] > 0)]

W         X         Y         Z
A  2.70685  0.628133  0.907969  0.503826

### f) Creating new columns

In [146]:
# With square brackets and a new column name
df['new'] = df['W'] + df['Y']
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355

### g) Deleting columns

In [147]:
df.drop(labels = 'new', axis = 1)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001

In [148]:
# Deletion is not "inplace" by default
df.columns

Index(['W', 'X', 'Y', 'Z', 'new'], dtype='object')

In [149]:
# ... either save as new
df1 = df.drop(labels = 'new', axis = 1)
df1.columns

Index(['W', 'X', 'Y', 'Z'], dtype='object')

In [150]:
# ... or set inplace = True
df.drop(labels = 'new', axis = 1, inplace = True)
df.columns

Index(['W', 'X', 'Y', 'Z'], dtype='object')

In [151]:
# ... or with del: deletion is done "inplace"
del df['Z']
df.columns

Index(['W', 'X', 'Y'], dtype='object')

###  h) Deleting rows

In [152]:
# Also with df.drop(), but axis = 0
df.drop(labels = 'C',
    axis = 0)

W         X         Y
A  2.706850  0.628133  0.907969
B  0.651118 -0.319318 -0.848077

In [153]:
# => The inplace behavior is similar to the columns
df

W         X         Y
A  2.706850  0.628133  0.907969
B  0.651118 -0.319318 -0.848077
C -2.018168  0.740122  0.528813

### i) Resetting the index

In [154]:
df # data frame from above

W         X         Y
A  2.706850  0.628133  0.907969
B  0.651118 -0.319318 -0.848077
C -2.018168  0.740122  0.528813

In [155]:
# With reset_index () the index is set back to 0, 1, ..., n-1
# and the original index is added as a new column
df.reset_index()

index         W         X         Y
0     A  2.706850  0.628133  0.907969
1     B  0.651118 -0.319318 -0.848077
2     C -2.018168  0.740122  0.528813

In [156]:
# drop = True prevents the old index from being added as a new column
df.reset_index(drop = True, inplace = True)

The **df.reset_index()** function in Python's pandas is used to reset a DataFrame's index to the default integer index. It's useful when the original index is altered (e.g., after sorting or filtering) or when you want to turn the current index into a column. This function is particularly helpful for handling MultiIndex DataFrames and improving the DataFrame's readability and accessibility.

Practical example:

In [157]:
# Create DataFrame df1
df1 = pd.DataFrame({
    'A': [1, 2, 3]
    }, index=[0, 1, 2])

# Create DataFrame df2
df2 = pd.DataFrame({
    'B': [4, 5, 6]
    }, index=[1, 2, 3])

# Concatenate df1 and df2 horizontally
result = pd.concat([df1, df2], axis=1)

In [158]:
# horizontal concatination of tables is orientated on the index of both tables
result

A    B
0  1.0  NaN
1  2.0  4.0
2  3.0  5.0
3  NaN  6.0

So if you concat tables, which have been e.g. sorted or filtered prior, you have to reset the index first.

## 2.3 Missing Values

In [159]:
df = pd.DataFrame({'A' : [1, 2, np.nan],
    'B' : [5, np.nan, np.nan],
    'C' : [1, 2, 3]})
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

### a) Removing missing values

In [160]:
df.dropna() # default: axis = 0 => keep only complete rows

A    B  C
0  1.0  5.0  1

In [161]:
# For columns: axis = 1
df.dropna(axis = 1)

C
0  1
1  2
2  3

### b) Finding missing values

In [162]:
df.isnull()

A      B      C
0  False  False  False
1  False   True  False
2   True   True  False

### c) Replacing missing values

In [163]:
df.fillna(value = 'ABC')

A    B  C
0  1.0  5.0  1
1  2.0  ABC  2
2  ABC  ABC  3

In [164]:
# Replace NAs in column A with their mean value (not inplace)
df['A'].fillna(value = df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

## 2.4 Groupby

### a) Grouping rows

In [165]:
# Create a data frame
data = {'Uni' : ['LMU','LMU','TU','TU','MIT','MIT'],
    'Name' : ['Sophie','Hans','Tanja','Ursula','Alice','Bob'],
    'Groesse': [189,195,185,169,175,177]}
df = pd.DataFrame(data)
df

Uni    Name  Groesse
0  LMU  Sophie      189
1  LMU    Hans      195
2   TU   Tanja      185
3   TU  Ursula      169
4  MIT   Alice      175
5  MIT     Bob      177

In [166]:
# With groupby(), the data frame is grouped line by line,
# the output seems a little less meaningful
df.groupby('Uni')

### b) Apply functions to groups

In [167]:
df.groupby('Uni')[['Groesse']].mean()

Groesse
Uni         
LMU    192.0
MIT    176.0
TU     177.0

In [168]:
by_uni = df.groupby('Uni')[['Groesse']]
by_uni.std()

Groesse
Uni           
LMU   4.242641
MIT   1.414214
TU   11.313708

In [169]:
by_uni.min() # Warning: rows do not belong together!

Groesse
Uni         
LMU      189
MIT      175
TU       169

## 2.5 Functions for DataFrames

### a) Brief overview of the dataset

In [170]:
df = pd.DataFrame({'col1' : [1,2,3,4],
    'col2' : [444,555,666,444],
    'col3' : ['abc','def','ghij','xyz']})

# Brief overview of data types, sizes, and missing values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   col1    4 non-null      int64 
 1   col2    4 non-null      int64 
 2   col3    4 non-null      object
dtypes: int64(2), object(1)
memory usage: 224.0+ bytes


In [171]:
# Dimension of the dataset
df.shape

(4, 3)

In [172]:
# Display the first 3 rows
df.head(n=3) # default n=5 implemented

col1  col2  col3
0     1   444   abc
1     2   555   def
2     3   666  ghij

In [173]:
# unique values
df['col2'].unique()

array([444, 555, 666])

In [174]:
# Number of unique values
df['col2'].nunique()

3

In [175]:
# Frequency table
df['col2'].value_counts()

col2
444    2
555    1
666    1
Name: count, dtype: int64

In [176]:
# Crosstab
pd.crosstab(df["col2"], df["col3"])

col3  abc  def  ghij  xyz
col2                     
444     1    0     0    1
555     0    1     0    0
666     0    0     1    0

### b) Application of functions

In [177]:
df['col1']*2

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [178]:
# Sum of column 1
df['col1'].sum()

10

In [179]:
# To have all the column sums, you don't need a loop:
df.sum()

col1               10
col2             2109
col3    abcdefghijxyz
dtype: object

In [180]:
# Warning: + is defined as concatenate for strings
df.select_dtypes(include=[int, float]).sum(axis=1) # The string column is excluded here by type selection

0    445
1    557
2    669
3    448
dtype: int64

In [181]:
# applying a function on a column - example len()
df['col3'].apply(len)

0    3
1    3
2    4
3    3
Name: col3, dtype: int64

In [182]:
# define your own function and apply
def foo(value: int):
    """
    function to substract 111
    """
    return value - 111

df['col2'].apply(foo)

0    333
1    444
2    555
3    333
Name: col2, dtype: int64

In Python's pandas library, the **apply()** function is used for applying a function along an axis of a DataFrame or on a Series. It is particularly useful for custom or complex operations that aren't covered by built-in methods. <br>
Compared to R, where many operations are inherently vectorized, Python relies more on **apply()** for these types of operations due to pandas DataFrames not being as intrinsically vectorized as R's data structures. This makes **apply()** a key tool in Python for flexible and customized data manipulation.

###  c) sort by

In [183]:
# sort_values(): inplace = False is the default again
# notice the index change
df.sort_values(by='col2')

col1  col2  col3
0     1   444   abc
3     4   444   xyz
1     2   555   def
2     3   666  ghij

## 2.6 Merging etc.

In [184]:
# append()
df = pd.DataFrame([[1, 2], [3, 4]], columns=list('AB'))
df

A  B
0  1  2
1  3  4

In [185]:
## 1 3 4
df2 = pd.DataFrame([[5, 6]], columns=list('AB'))
# df.append(df2) # append() is deprecated from pandas version 1.4.0 onwards
pd.concat([df,df2]) # vertically

A  B
0  1  2
1  3  4
0  5  6

In [186]:
pd.concat([df,df2], axis=1) # horizontially

A  B    A    B
0  1  2  5.0  6.0
1  3  4  NaN  NaN

# 3. Input and output

### a) csv

In [ ]:
# Get and Set the working directory at the top right (Spyder) or:
import os
os.getcwd()
# os.chdir('/Users/maxmuster/python-kurs')

In [ ]:
# Input
df = pd.read_csv('data/example.csv')

# Output
df.to_csv('data/example2.csv',
    index = False)

### b) Excel

In [ ]:
# Input
pd.read_excel('data/Excel_Sample.xlsx',
    sheet_name = 'Sheet1')

# Output
df.to_excel('data/Excel_Sample2.xlsx',
    sheet_name = 'Sheet1')